name: dependency_module
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.4
  flutter_modular: ^4.5.0
  mobx: ^2.0.6+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
