name: home_module
description: Home module.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.10.0"
dependencies:
  flutter:
    sdk: flutter
  sucrilhos_design_system:
    path: ../../sucrilhos_design_system
  dependency_module:
    path: ../../dependency_module
  core_module:
    path: ../../core_module
  game_module:
    path: ../game_module
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
