name: game_module
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sucrilhos_design_system:
    path: ../../sucrilhos_design_system
  dependency_module:
    path: ../../dependency_module
  core_module:
    path: ../../core_module
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
